### ISSUE TITLE
retrain runtime error: fail to load study

### ISSUE THREAD

**Issue by chuyuanli** [himkt/allenopt#35]
Hi @himkt again ^^

I had a problem when trying to run `allennlp retrain`, and I wish to ask for your help.

The command that I used for retrain:`allennlp retrain config/aa.jsonnet -s retrain_result/test --study-name test --include-package my_project --storage sqlite:///allennlp_optuna.db`

And I got this error:

> RuntimeError: Fail to load study. Perhaps you attempt to use `AllenNLPPruningCallback` without `AllenNLPExecutor`. If you want to use a callback without an executor, you have to instantiate a callback with`trial` and `monitor. Please see the Optuna example: https://github.com/optuna/optuna/blob/master/examples/allennlp/allennlp_simple.py.

I don't understand why it asked for a `Allennlpexecutor` here. And I checked with `optuna studies --storage sqlite:///allennlp_optuna.db`. The study is presented.

Related to this error, I also have some questions, hope you don't mind.
- I am not sure if I understand correctly the objectif of `retrain`. I firstly used "train-dev" and obtained some optimised parameters, then I use the same config on "train-test". Is it the aime of `retrain` command here?
- I followed the python script mentioned in the error [here](https://github.com/optuna/optuna/blob/master/examples/allennlp/allennlp_simple.py). Line 109 says that "# `patience=None` since it could conflict with AllenNLPPruningCallback". I thus changed `patience` in my trainer to None (I had `patience=5`) but I still have the same error. I am a bit confused by the `patience` parameter in trainer then. Can't I use it during `tune`? 
- I searched `retrain` in optuna docs but couldn't find anything similar. Is it only exists for cli?

 Thank you in advance!

**Comment by himkt** [comment]
Hi @chuyuanli. First of all, thank you for trying so much!
I assume you tried the following steps:

```bash
# simply search hyperparameter using allennlp-optuna
allennlp tune examples/allennlp/classifier.jsonnet hparams.json --serialization-dir hpo --n-trials 10 --study-name test

# then, re-train a model with the same configuration as one in `tune`
allennlp retrain examples/allennlp/classifier.jsonnet -s retrain --study-name test --storage sqlite:///allennlp_optuna.db
```

If it is the case, please copy your configuration file and simply remove `optuna_pruner` from `callbacks` section and use it for retraining like following:

```
cp examples/allennlp/classifier.jsonnet classifier_for_retraining.jsonnet
vim classifier_for_retraining.json  # remove `optuna_pruner`
allennlp retrain classifier_for_retraining.jsonnet -s retrain --study-name test --storage sqlite:///allennlp_optuna.db
```

It is because pruning functionality is only available in retraining. `allennlp retrain` simply load optimized hyperparameters and launch `allennlp train`, which means it is independent from Optuna. `optuna_pruner` is Optuna's feature. It doesn't work in the situation.

Later, I'll send a PR that automatically remove `optuna_pruner` in `allennlp retrain`. Sorry for the inconvenience.

---

> I firstly used "train-dev" and obtained some optimised parameters, then I use the same config on "train-test". Is it the aime of retrain command here?

The main purpose of the `retrain` is simply training a model with optimized hyperparameters. In other words, the result of retraining should be identical to the best trial in the study. `retrain` simply re-trains a model outside the Optuna's parameter searching.

> I followed the python script mentioned in the error here. Line 109 says that "# patience=None since it could conflict with AllenNLPPruningCallback". I thus changed patience in my trainer to None (I had patience=5) but I still have the same error. I am a bit confused by the patience parameter in trainer then. Can't I use it during tune?

Sorry, I may not understand your circumstance well. If you encountered the error in `retrain`, the solution could be removing `optuna_pruner` from the configuration. If you saw the error in `tune`, please tell me more about the situation.

> I searched retrain in optuna docs but couldn't find anything similar. Is it only exists for cli?

You're right. `tune` and `retrain` are the functionality of `allennlp-optuna`.

**Comment by himkt** [comment]
Let me close the issue. Feel free to reopen if you need.
