### ISSUE TITLE
Trials with repeated set of hyperparameters

### ISSUE THREAD

**Issue by pvcastro** [himkt/allenopt#44]
Hi @himkt !

I'm running other studies now, and I'm noticing that I'm getting a lot of trials with the exact same set of hyperparameters:

![image](https://user-images.githubusercontent.com/12713359/120070668-12393880-c062-11eb-88c8-2b9e515e0c4b.png)

This is just an example, but I've noticed this behavior in other studies.

I'm attaching here all my config files and the shell script I'm using to run the studies.

[allennlp-optuna-competicao (shell script).txt](https://github.com/himkt/allennlp-optuna/files/6564691/allennlp-optuna-competicao.shell.script.txt)
[optuna.json.txt](https://github.com/himkt/allennlp-optuna/files/6564692/optuna.json.txt)
[optuna_competicao_pass_through.jsonnet.txt](https://github.com/himkt/allennlp-optuna/files/6564693/optuna_competicao_pass_through.jsonnet.txt)
[search_space_pass_through_2.json.txt](https://github.com/himkt/allennlp-optuna/files/6564694/search_space_pass_through_2.json.txt)

Thanks!

**Comment by himkt** [comment]
A sampler could return the same parameter over trials. As a workaround, you can skip a trial and use a past trial for the reporting value.

https://stackoverflow.com/questions/58820574/how-to-sample-parameters-without-duplicates-in-optuna
https://github.com/optuna/optuna/issues/717

**Comment by pvcastro** [comment]
@himkt don't you think this is a bug? I don't understand why the optuna team didn't handle this as a bug. It doesn't make sense to run the same trial more than one time. In my scenarios here, I'm getting quite a waste of computational efforts...for one study I got the same set of parameters 45 times out of 137, and for the other I got 33 out of 95.

How do you feel about adding the suggestion from stackoverflow to allennlp-optuna? And enabling it according to a parameter. I like the `raise optuna.structs.TrialPruned('Duplicate parameter set')` suggestion better, how about you?

I can help with a PR, if you agree.

**Comment by himkt** [comment]
Yes, I think it is not a bug. An objective function has a noise in nature, and an algorithm could sample a point near the specific point to get more information around it. However, I understand your situation that too many trials searched the same point is not desirable.

TPE places significance on exploitation under the trade-off between exploitation and exploration. And TPE behaves like a majority voting on a histogram for a categorical variable (@hideakiimamura, Optuna core team member told me). He also told me that the optimization could be improved by converting your categorical variable into a discrete variable and using TPE with `multivariate=True`(For example, `lr` could be a discrete variable of floating points on [1e-5, 5e-5] with step 1. weight_decay is a little bit difficult but it could be a variable on floating points on [0.0, 0.3] in the log domain...).

> How do you feel about adding the suggestion from stackoverflow to allennlp-optuna?

I don't think it's good to introduce a duplicate parameter set logic to `allennlp-optuna` since this library is a thin wrapper of Optuna. If we introduce the trick, implementing it in Optuna would be better.

@hideakiimamura Please correct me if I wrote something wrong or could be modified. And do you think if we can support skipping evaluation of an objective function for a duplicated parameter set in Optuna?

**Comment by himkt** [comment]
Closed because it is not bug but Optuna specification.
